"""ISO-3166 country codes and names used by the geo choropleth.

Only the codes actually present in the compact /16 -> country table are
meaningful; this is the master list the generator indexes into.
"""

# ISO-3166 alpha-2 -> short name. Kept deliberately terse for the SVG
# choropleth legend and tooltips.
COUNTRIES = {
    "US": "United States",
    "CN": "China",
    "RU": "Russia",
    "IN": "India",
    "BR": "Brazil",
    "VN": "Vietnam",
    "TR": "Turkey",
    "DE": "Germany",
    "GB": "United Kingdom",
    "FR": "France",
    "NL": "Netherlands",
    "IT": "Italy",
    "ES": "Spain",
    "PL": "Poland",
    "SE": "Sweden",
    "NO": "Norway",
    "FI": "Finland",
    "DK": "Denmark",
    "BE": "Belgium",
    "CH": "Switzerland",
    "AT": "Austria",
    "CZ": "Czechia",
    "RO": "Romania",
    "GR": "Greece",
    "UA": "Ukraine",
    "BY": "Belarus",
    "KZ": "Kazakhstan",
    "UZ": "Uzbekistan",
    "GE": "Georgia",
    "AZ": "Azerbaijan",
    "AM": "Armenia",
    "IL": "Israel",
    "EG": "Egypt",
    "SA": "Saudi Arabia",
    "AE": "United Arab Emirates",
    "QA": "Qatar",
    "KW": "Kuwait",
    "IR": "Iran",
    "IQ": "Iraq",
    "SY": "Syria",
    "AF": "Afghanistan",
    "PK": "Pakistan",
    "BD": "Bangladesh",
    "MM": "Myanmar",
    "TH": "Thailand",
    "KH": "Cambodia",
    "LA": "Laos",
    "MY": "Malaysia",
    "SG": "Singapore",
    "ID": "Indonesia",
    "PH": "Philippines",
    "JP": "Japan",
    "KR": "South Korea",
    "KP": "North Korea",
    "TW": "Taiwan",
    "HK": "Hong Kong",
    "MX": "Mexico",
    "CA": "Canada",
    "AR": "Argentina",
    "CL": "Chile",
    "CO": "Colombia",
    "PE": "Peru",
    "VE": "Venezuela",
    "EC": "Ecuador",
    "BO": "Bolivia",
    "PY": "Paraguay",
    "UY": "Uruguay",
    "CU": "Cuba",
    "HT": "Haiti",
    "JM": "Jamaica",
    "DO": "Dominican Republic",
    "AU": "Australia",
    "NZ": "New Zealand",
    "ZA": "South Africa",
    "NG": "Nigeria",
    "KE": "Kenya",
    "GH": "Ghana",
    "ET": "Ethiopia",
    "MA": "Morocco",
    "DZ": "Algeria",
    "TN": "Tunisia",
    "SD": "Sudan",
    "UG": "Uganda",
    "ZW": "Zimbabwe",
    "ZM": "Zambia",
    "MZ": "Mozambique",
    "AO": "Angola",
    "CM": "Cameroon",
    "CI": "Ivory Coast",
    "SN": "Senegal",
    "ML": "Mali",
    "BF": "Burkina Faso",
    "NE": "Niger",
    "TD": "Chad",
    "SO": "Somalia",
    "LY": "Libya",
    "RS": "Serbia",
    "HR": "Croatia",
    "SI": "Slovenia",
    "SK": "Slovakia",
    "HU": "Hungary",
    "BG": "Bulgaria",
    "LT": "Lithuania",
    "LV": "Latvia",
    "EE": "Estonia",
    "IE": "Ireland",
    "PT": "Portugal",
    "LU": "Luxembourg",
    "CY": "Cyprus",
    "MT": "Malta",
    "IS": "Iceland",
    "CR": "Costa Rica",
    "PA": "Panama",
    "GT": "Guatemala",
    "SV": "El Salvador",
    "HN": "Honduras",
    "NI": "Nicaragua",
    "PR": "Puerto Rico",
    "NP": "Nepal",
    "LK": "Sri Lanka",
    "MN": "Mongolia",
    "KG": "Kyrgyzstan",
    "TJ": "Tajikistan",
    "TM": "Turkmenistan",
    "OM": "Oman",
    "YE": "Yemen",
    "JO": "Jordan",
    "LB": "Lebanon",
    "PS": "Palestine",
    "BH": "Bahrain",
    "MD": "Moldova",
    "MK": "North Macedonia",
    "AL": "Albania",
    "BA": "Bosnia and Herzegovina",
    "ME": "Montenegro",
    "XK": "Kosovo",
    "ZZ": "Unknown",
    "AQ": "Antarctica",
    "FJ": "Fiji",
    "PG": "Papua New Guinea",
    "SG2": "reserved",
}


def code_name(code):
    """Return a human-readable name for a country code, or the code itself."""
    return COUNTRIES.get(code, code)


def known_codes():
    """The set of codes the compact table can index into."""
    return sorted(COUNTRIES.keys())
